### ISSUE TITLE
Responsiveness of other pages

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#4] opened 2021-12-19 18:03 UTC

**Comment by arpit456jain** [comment] 2021-12-19 18:04
@Atif0604 check other pages too and make them responsive. try to make separate PRs
try to make 1 common css file for main layout like for navbar and footer

**Comment by Atif0604** [comment] 2021-12-19 18:27
Hey @arpit456jain there no issue with css but the problem is in the html files
I'll surely make all the pages responsive by making individuals PR for Individual pages

**Comment by arpit456jain** [comment] 2021-12-19 18:57
Ok cool

**Comment by Atif0604** [comment] 2021-12-22 13:23
Hey @arpit456jain you can close this now

**Comment by arpit456jain** [comment] 2021-12-26 10:54
@Atif0604 make a new issue and try to make a css file which contain css which is common to whole website same css is written every course folder

**Comment by Atif0604** [comment] 2021-12-26 13:25
Ok @arpit456jain I will a issue about this add a new common.css file in the root folder which common in all files

**Comment by Atif0604** [comment] 2021-12-29 10:11
You can close this now

**Closed** 2021-12-29 12:00 UTC
Labels: good first issue, open for all, swoc'22
