### ISSUE TITLE
Sign in and Sign up of the website not working

### ISSUE THREAD

**Issue by kiran11621** [arpit456jain/CodingEasy#137] opened 2022-03-01 14:39 UTC
I would love to work on sign in and sign up part of the project.

**Comment by kiran11621** [comment] 2022-03-01 14:59
Welcome, so is this issue assigned to me?

**Comment by Aditya3403** [comment] 2022-03-01 16:19
I would like to work on this issue. Kindly assign this issue to me.

**Comment by arpit456jain** [comment] 2022-03-01 21:49
@kiran11621 i hop u can implement the login and signup part

**Comment by kiran11621** [comment] 2022-03-02 09:45
Yes, Arpit Jain I can. Please do assign me.

**Comment by Aman16-ai** [comment] 2022-03-02 10:59
can u please assign me this issue

**Comment by HarshKumarChoudary** [comment] 2022-03-05 04:40
Please consider me next in the queue if the issue is not resolved. I'm a GSSOC22 participant

**Comment by rajat4885** [comment] 2022-03-06 03:39
I would like to work on this issue, can you please assign me? I am a GSSOC'22 participant.
Kindly assign me this issue.

**Closed** 2022-03-08 10:11 UTC
Labels: GSSoC22
