### ISSUE TITLE
bug in blog

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#389] opened 2022-05-25 04:37 UTC
### Description

![image](https://user-images.githubusercontent.com/55352601/170180777-9ea937a6-d66f-4ee7-ace1-551c15724123.png)
![image](https://user-images.githubusercontent.com/55352601/170180794-0941f494-eb22-45ca-96f9-d4a12f78a15c.png)

**Comment by arpit456jain** [comment] 2022-05-25 04:37
@muhammadgalhoum check it once

**Comment by muhammadgalhoum** [comment] 2022-05-25 07:10
If the problem is still with you, assign this issue to me and I will push my code in a PR 
@arpit456jain

**Comment by arpit456jain** [comment] 2022-05-25 13:08
I will try it once again and let you know

**Comment by arpit456jain** [comment] 2022-05-25 14:04
@muhammadgalhoum

**Comment by muhammadgalhoum** [comment] 2022-05-25 20:17
close this issue @arpit456jain

**Closed** 2022-05-26 04:37 UTC
Labels: bug, GSSoC22
