### ISSUE TITLE
integrate editors to run the code dynamically like w3school and codepen

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/CodingEasy#94] opened 2022-01-06 14:00 UTC

**Comment by Vaishnavi1411** [comment] 2022-02-28 18:07
Hii @arpit456jain I wish to work on this as a GSSOC 22 participant.
Can you please assign this to me!!

**Comment by arpit456jain** [comment] 2022-03-01 13:54
go ahead @Vaishnavi1411

**Comment by Vaishnavi1411** [comment] 2022-03-03 18:35
![editor-tour](https://user-images.githubusercontent.com/71778469/156629466-223e2a7e-c77d-4114-8701-c35401661cab.png)
Hii @arpit456jain !!
How does it looks, Can I create an editor like this using HTML, CSS, and JS...

**Comment by HarshKumarChoudary** [comment] 2022-03-05 04:41
Please consider me next in the queue if the issue is not resolved. I'm a GSSOC22 participant

**Comment by HarshKumarChoudary** [comment] 2022-03-05 04:42
@Vaishnavi1411 I guess you need to create a dynamic editor which displays the results. This could be done using APIs, just using HTML and CSS won't work.

**Comment by arpit456jain** [comment] 2022-03-08 18:06
> @Vaishnavi1411 I guess you need to create a dynamic editor which displays the results. This could be done using APIs, just using HTML and CSS won't work.

@Vaishnavi1411 he is right are u able to do it?

**Comment by Vaishnavi1411** [comment] 2022-03-08 18:42
Yes sir I know about API.I am able to do it.

**Comment by arpit456jain** [comment] 2022-03-09 09:00
ok @Vaishnavi1411 go ahead

**Comment by arpit456jain** [comment] 2022-03-18 10:02
@Vaishnavi1411 updates ?

**Comment by singhmansi25** [comment] 2022-03-25 14:50
@Vaishnavi1411 
please update about your status of work.
Or else we will assign people waiting in queue to complete this issue.

**Comment by arpit456jain** [comment] 2022-03-26 04:19
@HarshKumarChoudary r u interested ?

**Comment by HarshKumarChoudary** [comment] 2022-03-26 04:36
yes I could work on it.

**Comment by Vaishnavi1411** [comment] 2022-03-26 04:49
@arpit456jain I am working on it and I have shown the output to @singhmansi25  on discord!

**Comment by singhmansi25** [comment] 2022-03-26 04:55
@arpit456jain 
Please let @Vaishnavi1411 to complete this by this week.
If she couldn't then may be we can assign to others.
**@Vaishnavi1411 
Please share your status of work here.**

**Comment by Vaishnavi1411** [comment] 2022-03-26 05:00
ok @singhmansi25

**Comment by Vaishnavi1411** [comment] 2022-03-26 05:01
![ss](https://user-images.githubusercontent.com/71778469/160225449-7a986857-602e-402c-92d0-664d9a9712a8.png)

**Comment by Vaishnavi1411** [comment] 2022-03-26 05:02
![editor](https://user-images.githubusercontent.com/71778469/160225480-32f78aa2-79d5-45c0-89e7-45c8bcbc9668.png)

**Comment by arpit456jain** [comment] 2022-03-26 07:17
Ok @Vaishnavi1411 make PR asap..

@HarshKumarChoudary wait for 1-2 days 
After that you can work on this issue or improve the work done by her

**Comment by Vaishnavi1411** [comment] 2022-03-26 08:50
Ok @arpit456jain

**Comment by Vaishnavi1411** [comment] 2022-03-28 08:42
Please review my PR.

**Comment by singhmansi25** [comment] 2022-03-28 14:57
@Vaishnavi1411 
Reviewed.
@arpit456jain 
Please check the PR once.

**Comment by arpit456jain** [comment] 2022-04-04 11:39
@Vaishnavi1411  make PR asap

**Comment by arpit456jain** [comment] 2022-04-04 11:56
@singhmansi25 contact to her if she is unable to make PR and doesn't respond in 2 days assign this issue to @HarshKumarChoudary

**Comment by Vaishnavi1411** [comment] 2022-04-04 18:53
Review my PR @arpit456jain

**Closed** 2022-04-10 05:18 UTC
Labels: GSSoC22, Level2
